# Generated by Django 4.2.7 on 2023-12-08 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 8, 10, 29, 401166, tzinfo=datetime.timezone.utc)),
        ),
    ]
