# Generated by Django 4.2.7 on 2023-12-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0006_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.FileField(null=True, upload_to='blogfiles'),
        ),
    ]
