# Generated by Django 4.2.7 on 2023-12-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0007_article_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.SlugField(max_length=70),
        ),
    ]
