# Generated by Django 4.2.7 on 2024-01-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0010_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-updated', '-created')},
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
